add functionality for --force-parent-span-id
equinix-labs/otel-cli pull request #241
Opened 2023-07-13 14:53 UTC by domofactor

similar to `--force-trace-id` and `--force-span-id`, this PR adds the ability to specify `--force-parent-span-id` or `OTEL_CLI_FORCE_PARENT_SPAN_ID` to override a parent span id.

cc/ https://github.com/equinix-labs/otel-cli/issues/240

2023-07-13 17:09 UTC, tobert approved these changes
PR overall is high quality and matches the code around it. Thank you!

The "parentdeadbeef" issue I noted in comments is a mistake I made in `parseHex()` or elsewhere that will need a follow-up. I'm inclined to merge this as-is, and follow up with another PR to fix the hex parsing issue.

2023-07-13 17:09 UTC, tobert commented on data_for_test.go
> +					"--force-parent-span-id", "parentbeefcafede",
following off prior comment, if this passes, we have a test & safety gap allowing non-hex to pass through

2023-07-13 18:04 UTC, tobert requested changes
My bad for thinking tests passed before. They don't. I think if you update the test case to be hex it'll work fine.

2023-07-14 05:53 UTC, domofactor commented
hey @tobert, thanks for the feedback. I pushed that change from string to hex, so hopefully it should pass now. 🤞

2023-07-14 15:36 UTC, tobert commented on README.md
> +| --force-parent-span-id | OTEL_CLI_FORCE_PARENT_SPAN_ID       | force_parent_span_id     | p4r3ntb33fc4f3d3 |
```suggestion
| --force-parent-span-id | OTEL_CLI_FORCE_PARENT_SPAN_ID       | force_parent_span_id     | eeeeeeb33fc4f3d3 |
```

2023-07-14 15:37 UTC, tobert commented on data_for_test.go
> +					"parent_span_id": "p4r3ntb33fc4f3d3",
```suggestion
					"parent_span_id": "e4e3eeb33fc4f3d3",
```

2023-07-14 15:37 UTC, tobert commented on data_for_test.go
> +					"--force-parent-span-id", "p4r3ntb33fc4f3d3",
```suggestion
					"--force-parent-span-id", "e4e3eeb33fc4f3d3",
```

2023-07-14 15:48 UTC, tobert approved these changes
I pushed a few more changes and a fix to get this ready to merge. Thanks!

2023-07-14 15:49 UTC, merged