Don't fail on err in exec
equinix-labs/otel-cli pull request #259
Opened 2023-08-31 23:02 UTC by parsonsmatt

Fixes #258 

I'm having a hard time writing a test for this.

2023-09-13 14:05 UTC, tobert requested changes
If you have time to work on this, I've provided some notes that should help you make progress. If you don't have time, LMK and I'll finish it up.

2023-09-13 14:05 UTC, tobert commented on otelcli/exec.go
> +                        Message: fmt.Sprintln("exec command failed: ", err),
I'd just do fmt.Sprintf here, message doesn't need the newline.

2023-09-13 14:05 UTC, tobert commented on data_for_test.go
> +        // },
Hmmm this test looks right.

Try adding `"--fail", "--verbose"` to the CliArgs. It looks like `config.SoftFail` is being called when child.Run() returns an err.

> If the command starts but does not complete successfully, the error is of type *ExitError. Other error types may be returned for other situations.

so the `if err :- child.Run(); err != nil` needs to be expanded to check for ExitError and not SoftFail on that so you can send the error upstream in the span status.

2023-09-13 16:09 UTC, parsonsmatt commented
Unfortunately, I don't have further cycles to put towards this. Thanks for the review and the time/effort you've spent on this tool!

2023-09-15 20:11 UTC, tobert commented
Thanks for the PR! Work is busy right now so it might take me a couple weeks but I'll get this in and release.

2023-09-21 21:33 UTC, tobert approved these changes
Thanks for getting this started!

It turned out the test code that examines exit status needed some rework to test this, so I added that to your PR.

2023-09-21 21:33 UTC, merged